name: Automatyczne Testy Aplikacji

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main" ]

jobs:
  run-tests:
    runs-on: ubuntu-latest  

    steps:
    - name: Pobieranie kodu źródłowego
      uses: actions/checkout@v4


    - name: Konfiguracja środowiska Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'



    - name: Instalacja bibliotek
      run: npm install

    - name: Uruchomienie testów automatycznych
      run: npm test
